version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  allow:
  - dependency-type: all
    dependency-name: "*"
  assignees: [thetechnick]
  open-pull-requests-limit: 100
